[package]
name        = "win_msgbox_timeout"
authors     = ["Mikachu2333"]
license     = "MIT"
version     = "1.1.1"
edition     = "2024"
description = "Windows message boxes and notification helpers with timeout for Rust"
readme      = "README.md"
repository  = "https://github.com/Mikachu2333/win_msgbox"
keywords    = ["windows", "messagebox", "notification", "win32"]
categories  = ["os::windows-apis", "gui"]

[lib]
name = "win_msgbox_timeout"
path = "lib.rs"
